version: '3.9'

services:
  mistral-chatbot:
    build: .
    ports:
      - "7860:7860"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    container_name: mistral-chatbot-ui
